# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e38ae480c5894d38afad75a71b7e2125b8bce80cc95e5245f30179f2f6db034f21b0e57d684a541be9a474d7c4bfc0ff2d0f83d1d0ceaa26bc97d1482ab0e17e

test:
  secret_key_base: 86b7666f72e99052926e5216caec81f5071a4c599f7c23dc61400831fb2215e678f10736c606f6a92bbecbccf010cb14aa5c28936c0ba4522afb1710556a29b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
